### ISSUE TITLE
3.1 issues

### ISSUE THREAD

**Issue by ARNHOE** [tractorcow/silverstripe-robots#4]
My robots.txt is returning

```
User-agent: *
Disallow: /
```

My robots.yml

```

---
Name: myrobotsconfiguration

---
Robots:
  sitemap: '/sitemap.xml'
  disallow_unsearchable: true
  disallowed_urls:
    - '/admin'
    - '/Security'
  allowed_urls: []
```

Using master branch on 3.1 with Fluent :)
